#!/usr/bin/env bash
# This script displays numbers and associated messages based on the loop iteration

num=1
while [ "$num" -le 20 ]; do
    case $num in
        4)
            echo $num
            echo "and then bad luck from China"
            ;;
        9)
            echo $num
            echo "and then bad luck from Japan"
            ;;
        17)
            echo $num
            echo "and then bad luck from Italy"
            ;;
        *)
            echo $num
            ;;
    esac
    ((num++))
done
